package cli

import (
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

func TestRenderSkill_StampsVersionAndCoversLoop(t *testing.T) {
	oldVersion := rootCmd.Version
	rootCmd.Version = "v9.8.7"
	defer func() { rootCmd.Version = oldVersion }()

	content := renderSkill(rootCmd)
	if !strings.HasPrefix(content, "---\nname: monodev\ndescription: ") {
		t.Fatalf("skill must start with Agent Skills frontmatter naming the directory:\n%s", content)
	}
	for _, want := range []string{
		`monodev-version: "v9.8.7"`,
		"Generated by monodev v9.8.7",
		"monodev skill init --force",
		"`monodev context`",
		".agents/notes/lessons.md",
		".agents/notes/sessions/<date>-<agent>-<id>.md",
		".agents/scripts/",
		"delete the session file",
		"`monodev save`",
		"Never `git add`",
		"`monodev apply`",
		"notes can be stale",
		"deletes the store's files from the checkout",
		"Do not pass `--force`",
		"ADRs",
		"reviewed, committed repository docs",
		"`monodev checkout -n <store>`",
	} {
		if !strings.Contains(content, want) {
			t.Errorf("skill content missing %q", want)
		}
	}
	// Command lines come from the command tree, not a hard-coded copy.
	if !strings.Contains(content, "- `monodev apply [store-id...]`: "+applyCmd.Short) {
		t.Errorf("skill content does not render apply from the command tree:\n%s", content)
	}
}

func TestRenderSkill_CommandExamplesUseRegisteredSurface(t *testing.T) {
	path := filepath.Join(t.TempDir(), "SKILL.md")
	var lines []string
	for _, line := range strings.Split(renderSkill(rootCmd), "\n") {
		// Lift every inline `monodev ...` span onto its own line so the
		// shared documentation check validates each command and flag.
		for i, span := range strings.Split(line, "`") {
			if i%2 == 1 && strings.HasPrefix(span, "monodev ") {
				lines = append(lines, span)
			}
		}
	}
	if len(lines) == 0 {
		t.Fatal("skill names no monodev commands")
	}
	if err := os.WriteFile(path, []byte(strings.Join(lines, "\n")+"\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	assertDocumentedCommandsMatchBinary(t, path)
}

func TestResolveSkillTargets(t *testing.T) {
	claudePath := filepath.Join(".claude", "skills", "monodev", "SKILL.md")
	agentsPath := filepath.Join(".agents", "skills", "monodev", "SKILL.md")

	root := t.TempDir()
	if _, err := resolveSkillTargets(root, ""); err == nil || !strings.Contains(err.Error(), "--target") {
		t.Fatalf("no agent directory error = %v, want a --target hint", err)
	}
	if err := os.Mkdir(filepath.Join(root, ".agents"), 0o755); err != nil {
		t.Fatal(err)
	}
	if got, err := resolveSkillTargets(root, ""); err != nil || !reflect.DeepEqual(got, []string{agentsPath}) {
		t.Fatalf("default with .agents = %v, %v", got, err)
	}
	if err := os.Mkdir(filepath.Join(root, ".claude"), 0o755); err != nil {
		t.Fatal(err)
	}
	if got, err := resolveSkillTargets(root, ""); err != nil || !reflect.DeepEqual(got, []string{claudePath, agentsPath}) {
		t.Fatalf("default with both = %v, %v", got, err)
	}
	if got, err := resolveSkillTargets(t.TempDir(), "claude"); err != nil || !reflect.DeepEqual(got, []string{claudePath}) {
		t.Fatalf("--target claude = %v, %v", got, err)
	}
	if got, err := resolveSkillTargets(t.TempDir(), "all"); err != nil || !reflect.DeepEqual(got, []string{claudePath, agentsPath}) {
		t.Fatalf("--target all = %v, %v", got, err)
	}
	if _, err := resolveSkillTargets(root, "cursor"); err == nil {
		t.Fatal("--target cursor should be rejected")
	}
}

func TestSkillInit_RequiresActiveStore(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	t.Setenv("MONODEV_ROOT", "")
	configureTestGitIdentity(t)
	repo := initGitRepo(t, t.TempDir(), "https://example.com/monodev.git")
	runGit(t, repo, "commit", "--allow-empty", "-m", "initial")
	if err := os.Mkdir(filepath.Join(repo, ".claude"), 0o755); err != nil {
		t.Fatal(err)
	}
	chdir(t, repo)

	err := runCLIErr(t, "skill", "init")
	if err == nil || !strings.Contains(err.Error(), "monodev checkout -n <store>") {
		t.Fatalf("skill init without a store error = %v, want a checkout hint", err)
	}
	if _, statErr := os.Stat(filepath.Join(repo, ".claude", "skills")); !os.IsNotExist(statErr) {
		t.Fatalf("refused skill init wrote files: %v", statErr)
	}
}

func TestSkillInit_TracksSnapshotsAndHidesSkill(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	t.Setenv("MONODEV_ROOT", "")
	configureTestGitIdentity(t)
	repo := initGitRepo(t, t.TempDir(), "https://example.com/monodev.git")
	runGit(t, repo, "commit", "--allow-empty", "-m", "initial")
	if err := os.Mkdir(filepath.Join(repo, ".claude"), 0o755); err != nil {
		t.Fatal(err)
	}
	chdir(t, repo)
	runCLI(t, "checkout", "-n", "agent-context")

	out := runCLI(t, "skill", "init", "--json")
	var result struct {
		Store     string   `json:"store"`
		Written   []string `json:"written"`
		Committed []string `json:"committed"`
	}
	if err := json.Unmarshal([]byte(out), &result); err != nil {
		t.Fatalf("skill init JSON: %v\n%s", err, out)
	}
	skillPath := filepath.Join(".claude", "skills", "monodev", "SKILL.md")
	if result.Store != "agent-context" || !reflect.DeepEqual(result.Written, []string{skillPath}) || !reflect.DeepEqual(result.Committed, []string{skillPath}) {
		t.Fatalf("skill init result = %#v", result)
	}
	if status := gitPorcelain(t, repo); status != "" {
		t.Fatalf("git status after skill init = %q, want clean", status)
	}
	written, err := os.ReadFile(filepath.Join(repo, skillPath))
	if err != nil {
		t.Fatal(err)
	}
	if string(written) != renderSkill(rootCmd) {
		t.Fatal("written skill differs from skill show content")
	}
	show := runCLI(t, "skill", "show")
	if show != string(written) {
		t.Fatalf("skill show output differs from the written skill:\n%s", show)
	}

	if err := runCLIErr(t, "skill", "init"); err == nil || !strings.Contains(err.Error(), "--force") {
		t.Fatalf("second skill init error = %v, want a --force refusal", err)
	}

	if err := os.WriteFile(filepath.Join(repo, skillPath), []byte("stale\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	runCLI(t, "skill", "init", "--force", "--target", "all")
	rewritten, err := os.ReadFile(filepath.Join(repo, skillPath))
	if err != nil {
		t.Fatal(err)
	}
	if string(rewritten) != renderSkill(rootCmd) {
		t.Fatal("skill init --force did not rewrite the stale skill")
	}
	if _, err := os.Stat(filepath.Join(repo, ".agents", "skills", "monodev", "SKILL.md")); err != nil {
		t.Fatalf("--target all did not write the Agent Skills target: %v", err)
	}
	if status := gitPorcelain(t, repo); status != "" {
		t.Fatalf("git status after skill init --force = %q, want clean", status)
	}

	// The snapshot is real: unapply removes the skill and apply restores it.
	runCLI(t, "unapply")
	if _, err := os.Stat(filepath.Join(repo, skillPath)); !os.IsNotExist(err) {
		t.Fatalf("unapply left the skill in place: %v", err)
	}
	runCLI(t, "apply")
	restored, err := os.ReadFile(filepath.Join(repo, skillPath))
	if err != nil || string(restored) != renderSkill(rootCmd) {
		t.Fatalf("apply did not restore the skill: %v", err)
	}
}

func TestSkillInit_CommitsCoveringTrackedDirectory(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	t.Setenv("MONODEV_ROOT", "")
	configureTestGitIdentity(t)
	repo := initGitRepo(t, t.TempDir(), "https://example.com/monodev.git")
	runGit(t, repo, "commit", "--allow-empty", "-m", "initial")
	if err := os.MkdirAll(filepath.Join(repo, ".claude"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(repo, ".claude", "settings.json"), []byte("{}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	chdir(t, repo)
	runCLI(t, "checkout", "-n", "agent-context")
	runCLI(t, "track", "--agents")

	out := runCLI(t, "skill", "init", "--json")
	var result struct {
		Tracked   []string `json:"tracked"`
		Committed []string `json:"committed"`
	}
	if err := json.Unmarshal([]byte(out), &result); err != nil {
		t.Fatalf("skill init JSON: %v\n%s", err, out)
	}
	if len(result.Tracked) != 0 || !reflect.DeepEqual(result.Committed, []string{".claude"}) {
		t.Fatalf("skill init result = %#v, want the tracked .claude directory committed", result)
	}
	if status := gitPorcelain(t, repo); status != "" {
		t.Fatalf("git status after skill init = %q, want clean", status)
	}
}
